spring.application.name=demo
# Cloudinary Ayarlar
cloudinary.cloud-name=dkevpkym5
cloudinary.api-key=254323867342592
cloudinary.api-secret=2GmZdwI5xtIaxLhPY4LzYNxTKxs

# Buyuk dosya (video/fotograf) yuklemeleri icin Spring Boot limitlerini artirmaniz gerekir
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB