spring.application.name=demo
# Cloudinary Ayarlar
cloudinary.cloud-name=dkevpkym5
cloudinary.api-key=254323867342592
cloudinary.api-secret=2GmZdwI5xtIaxLhPY4LzYNxTKxs

# Büyük dosya (video/foto?raf) yüklemeleri için Spring Boot limitlerini art?rman?z gerekir
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB